[package]
name = "alloc_hater"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arbitrary = { version = "1.1.3", features = ["derive"] }
quickcheck = "1.0.3"
