[package]
name = "buddy"
version = "0.1.0"
edition = "2021"

[features]
default = ["sptr"]

alloc = []

# Enables nightly-only unstable Rust features.
unstable = []

[dependencies]
sptr = { version = "0.3.0", optional = true }

[dev-dependencies]
quickcheck = "1.0.3"
