on: [push, pull_request]

name: Continuous integration

jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - sptr
          - sptr,alloc
          - unstable
          - unstable,alloc
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --no-default-features --features=${{ matrix.features }} -- -D warnings

  test_stable:
    name: test (stable)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - sptr
          - sptr,alloc
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test --workspace
          args: --no-default-features --features=${{ matrix.features }}

  test_nightly:
    name: test (stable)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - sptr
          - sptr,alloc
          - unstable
          - unstable,alloc
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test --workspace
          args: --no-default-features --features=${{ matrix.features }}
